{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "galley-agent.serviceAccountName" . }}
  labels:
    {{- include "galley-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "galley-agent.fullname" . }}-nodes-reader
  labels:
    {{- include "galley-agent.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "galley-agent.fullname" . }}-nodes-reader
  labels:
    {{- include "galley-agent.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "galley-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "galley-agent.fullname" . }}-nodes-reader
  apiGroup: rbac.authorization.k8s.io
